version: '3.7'

services:
  db:
    image: mysql
    restart: always
    container_name: security_db
    environment:
      MYSQL_DATABASE: 'security-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '3306:3306'